Copy-Item .\node_modules\typescript\lib\lib.d.ts -Destination .\official-lib-declarations\lib.d.ts
Copy-Item .\node_modules\typescript\lib\lib.es2015.collection.d.ts -Destination .\official-lib-declarations\lib.es2015.collection.d.ts
Copy-Item .\node_modules\typescript\lib\lib.es2015.core.d.ts -Destination .\official-lib-declarations\lib.es2015.core.d.ts
Copy-Item .\node_modules\typescript\lib\lib.es2015.promise.d.ts -Destination .\official-lib-declarations\lib.es2015.promise.d.ts
Copy-Item .\node_modules\typescript\lib\lib.es2015.reflect.d.ts -Destination .\official-lib-declarations\lib.es2015.reflect.d.ts
Copy-Item .\node_modules\typescript\lib\lib.es2016.array.include.d.ts -Destination .\official-lib-declarations\lib.es2016.array.include.d.ts
Copy-Item .\node_modules\typescript\lib\lib.es2017.object.d.ts -Destination .\official-lib-declarations\lib.es2017.object.d.ts
Copy-Item .\node_modules\typescript\lib\lib.es2017.string.d.ts -Destination .\official-lib-declarations\lib.es2017.string.d.ts
Copy-Item .\node_modules\typescript\lib\lib.es2017.typedarrays.d.ts -Destination .\official-lib-declarations\lib.es2017.typedarrays.d.ts
Copy-Item .\node_modules\typescript\lib\lib.es2018.promise.d.ts -Destination .\official-lib-declarations\lib.es2018.promise.d.ts
